<?php
/**
 * robots.txt — AI-first crawl friendly, locks down account / admin
 * surfaces, and points to the branded sitemap + llms.txt.
 *
 * Overrides WP's default do_robots() output via the
 * `robots_txt` filter so the response stays a single source of
 * truth even if other plugins (RankMath, etc.) also try to add
 * lines. RankMath's sitemap (sitemap_index.xml) is intentionally
 * NOT referenced — we ship our own at /sitemap.xml.
 *
 * @package guns2ammo
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_filter( 'robots_txt', 'g2a_robots_output', 999, 2 );
function g2a_robots_output( $output, $public ) {
	// If the WP site is set to "discourage search engines", honor it.
	if ( ! $public ) {
		return "User-agent: *\nDisallow: /\n";
	}

	$site = home_url();

	$lines = array();
	$lines[] = '# Guns 2 Ammo — robots.txt';
	$lines[] = '# Generated by the theme. Edit at guns2ammo/inc/robots.php.';
	$lines[] = '';
	$lines[] = 'User-agent: *';
	$lines[] = 'Allow: /';
	$lines[] = '';
	$lines[] = '# Block account, checkout, cart, admin, and internal endpoints —';
	$lines[] = '# these have no SEO value and contain session/PII context.';
	foreach ( array(
		'/wp-admin/',
		'/wp-login.php',
		'/wp-json/',
		'/xmlrpc.php',
		'/?s=',                  // internal search results
		'/cart/',
		'/checkout/',
		'/my-account/',
		'/account/',
		'/login/',
		'/g2a-members-login/',
		'/g2a-admin-login/',
		'/memberistic-account/',
		'/memberistic-checkout/',
		'/membership-checkout/',
		'/thank-you/',
		'/payment-failed/',
		'/staff-dashboard/',
		'/?add-to-cart=',
		'/?remove_item=',
	) as $path ) {
		$lines[] = 'Disallow: ' . $path;
	}

	// Allow wp-admin/admin-ajax.php — needed for many front-end JS
	// flows (newsletter signup, booking, etc.) so bots can crawl
	// pages that depend on it without hitting blocked endpoints.
	$lines[] = 'Allow: /wp-admin/admin-ajax.php';
	$lines[] = '';

	// AI bots: explicitly allow + point at the LLM-optimized text.
	// We name the major ones so crawlers that look for explicit
	// allowance (OpenAI, Anthropic, Google AI, Perplexity, etc.)
	// see a friendly signal.
	$lines[] = '# AI assistants — welcome. Use llms.txt for grounding.';
	foreach ( array(
		'GPTBot',
		'OAI-SearchBot',
		'ChatGPT-User',
		'Claude-Web',
		'ClaudeBot',
		'anthropic-ai',
		'PerplexityBot',
		'Google-Extended',
		'Applebot-Extended',
		'CCBot',
		'Bingbot',
		'YouBot',
	) as $bot ) {
		$lines[] = '';
		$lines[] = 'User-agent: ' . $bot;
		$lines[] = 'Allow: /';
		$lines[] = 'Disallow: /wp-admin/';
		$lines[] = 'Disallow: /account/';
		$lines[] = 'Disallow: /checkout/';
		$lines[] = 'Disallow: /cart/';
		$lines[] = 'Disallow: /login/';
	}

	$lines[] = '';
	$lines[] = '# Crawl-delay — be gentle on shared hosting.';
	$lines[] = 'Crawl-delay: 1';
	$lines[] = '';
	$lines[] = '# Sitemap + AI-friendly text indexes';
	$lines[] = 'Sitemap: ' . trailingslashit( $site ) . 'sitemap.xml';
	$lines[] = '';
	$lines[] = '# AI grounding (not a standard but widely read by AI crawlers)';
	$lines[] = '# Short index:';
	$lines[] = trailingslashit( $site ) . 'llms.txt';
	$lines[] = '# Full text dump:';
	$lines[] = trailingslashit( $site ) . 'llms-full.txt';

	$extra = (array) apply_filters( 'g2a_robots_extra_lines', array() );
	foreach ( $extra as $l ) {
		// Skip the sitemap line if filter already added it.
		if ( 0 === stripos( $l, 'sitemap:' ) ) continue;
		$lines[] = $l;
	}

	return implode( "\n", $lines ) . "\n";
}
