<?php
/**
 * robots.txt — AI-first crawl friendly, locks down account / admin,
 * points to the branded sitemap + llms.txt.
 *
 * The client reported that even after activating the theme + the
 * RankMath sitemap module disabled, /robots.txt was still rendering
 * RankMath's content. Two reasons that happens:
 *   1. RankMath registers a `robots_txt` filter and a `parse_request`
 *      handler that emit its own output regardless of who else
 *      hooks the filter — its priority + handler scheme can win.
 *   2. WP's virtual `robots.txt` runs through `do_robots()` which
 *      itself is hooked to `do_robotstxt` action — and other
 *      plugins may short-circuit by sending output + exiting before
 *      our filter ever runs.
 *
 * Fix: intercept the URL DIRECTLY in `parse_request` at priority 0,
 * before WP even gets a chance to dispatch to `do_robots()` or any
 * plugin's hook. We send our own output and exit. No filter
 * priority war.
 *
 * @package guns2ammo
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'parse_request', 'g2a_robots_intercept', 0 );
function g2a_robots_intercept( $wp ) {
	$uri = isset( $_SERVER['REQUEST_URI'] )
		? (string) wp_parse_url( wp_unslash( $_SERVER['REQUEST_URI'] ), PHP_URL_PATH )
		: '';
	if ( strtolower( rtrim( $uri, '/' ) ) !== '/robots.txt' ) {
		return;
	}
	header( 'Content-Type: text/plain; charset=utf-8' );
	header( 'Cache-Control: public, max-age=3600' );
	echo g2a_robots_body(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	exit;
}

/* Belt-and-suspenders: also win the `robots_txt` filter in case any
   downstream code calls do_robots() directly. */
add_filter( 'robots_txt', 'g2a_robots_filter', PHP_INT_MAX, 2 );
function g2a_robots_filter( $output, $public ) {
	if ( ! $public ) {
		return "User-agent: *\nDisallow: /\n";
	}
	return g2a_robots_body();
}

function g2a_robots_body() {
	$site  = untrailingslashit( home_url() );

	$lines   = array();
	$lines[] = '# Guns 2 Ammo — robots.txt';
	$lines[] = '# Generated by the theme (guns2ammo/inc/robots.php).';
	$lines[] = '# This file is the SINGLE source of truth for crawl rules.';
	$lines[] = '';
	$lines[] = 'User-agent: *';
	$lines[] = 'Allow: /';
	$lines[] = '';
	$lines[] = '# Account / cart / admin — never useful for SEO.';
	$private_paths = function_exists( 'g2a_private_robots_paths' )
		? g2a_private_robots_paths()
		: array( '/wp-admin/', '/wp-login.php', '/account/', '/checkout/', '/cart/', '/login/' );
	foreach ( $private_paths as $path ) {
		$lines[] = 'Disallow: ' . $path;
	}
	$lines[] = 'Allow: /wp-admin/admin-ajax.php';
	$lines[] = '';

	// AI assistants — explicit allow + same private-path block so
	// they don't try to crawl checkout, account, login.
	$lines[] = '# AI assistants — welcome. Use llms.txt for grounding.';
	foreach ( array(
		'GPTBot',
		'OAI-SearchBot',
		'ChatGPT-User',
		'Claude-Web',
		'ClaudeBot',
		'anthropic-ai',
		'PerplexityBot',
		'Perplexity-User',
		'Google-Extended',
		'Applebot-Extended',
		'CCBot',
		'Bingbot',
		'YouBot',
		'DuckDuckBot',
		'YandexBot',
		'Amazonbot',
		'cohere-ai',
		'Bytespider',
		'Meta-ExternalAgent',
	) as $bot ) {
		$lines[] = '';
		$lines[] = 'User-agent: ' . $bot;
		$lines[] = 'Allow: /';
		foreach ( $private_paths as $path ) {
			$lines[] = 'Disallow: ' . $path;
		}
		$lines[] = 'Allow: /wp-admin/admin-ajax.php';
	}

	$lines[] = '';
	// NOTE: no Crawl-delay (Googlebot ignores it and Search Console flags
	// it as an error) and no bare URLs (anything that isn't a directive is
	// invalid robots syntax — GSC reported both). AI bots discover llms.txt
	// by convention at the site root; it must not be listed here.
	$lines[] = '# Sitemap (theme-owned — NOT RankMath\'s sitemap_index.xml).';
	$lines[] = 'Sitemap: ' . $site . '/sitemap.xml';

	$extra = (array) apply_filters( 'g2a_robots_extra_lines', array() );
	foreach ( $extra as $l ) {
		if ( 0 === stripos( $l, 'sitemap:' ) ) continue;
		$lines[] = $l;
	}

	return implode( "\n", $lines ) . "\n";
}
