#!/usr/bin/env bash
# Regenerate the self-hosted brand fonts under guns2ammo/assets/fonts/
# and rebuild guns2ammo/assets/css/fonts.css from the latest Google
# Fonts CSS response.
#
# Usage: ./scripts/fetch-fonts.sh
#
# Network: pulls from fonts.googleapis.com + fonts.gstatic.com.
# Output:  10 WOFF2 files in assets/fonts/ (latin subset) and a fresh
#          assets/css/fonts.css with local url() references.

set -euo pipefail
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$ROOT/guns2ammo"

FONT_DIR="assets/fonts"
CSS_OUT="assets/css/fonts.css"
mkdir -p "$FONT_DIR" "$(dirname "$CSS_OUT")"

UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125 Safari/537.36"
GF_URL='https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Barlow+Condensed:wght@500;600;700&family=Barlow:wght@400;500;600&family=DM+Sans:wght@400;500;700&family=Space+Mono:wght@400;700&display=swap'

tmp_css="$( mktemp )"
echo "→ Fetching Google Fonts CSS"
curl -sS -A "$UA" -o "$tmp_css" "$GF_URL"

echo "→ Filtering to latin subset + extracting WOFF2 URLs"
python3 - <<PY > "$CSS_OUT"
import re
src = open("$tmp_css").read()
blocks = re.findall(r'/\*\s*([a-z\-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})', src, re.S)
latin = [b for s,b in blocks if s == 'latin']
def repl(m):
    full = m.group(0)
    parts = full.split('/')
    return f'../fonts/{parts[-2]}-{parts[-1]}'
out = re.sub(r'https://fonts\.gstatic\.com/[^)\s]+', repl, "\n\n".join(latin))
print("/* G2A self-hosted brand fonts — generated by scripts/fetch-fonts.sh */\n")
print(out)
PY

echo "→ Downloading WOFF2 files into $FONT_DIR/"
urls=$( grep -oE 'https://fonts\.gstatic\.com/[^)]+' "$tmp_css" | python3 -c '
import sys, re
src = sys.stdin.read()
print("\n".join(sorted(set(
    u for u in re.findall(r"https://fonts\.gstatic\.com/[^)\s]+", src)
    if "/s/" in u
))))' )

new=0
while IFS= read -r url; do
  [ -z "$url" ] && continue
  fname=$( echo "$url" | awk -F/ '{print $(NF-1)"-"$NF}' )
  if [ ! -f "$FONT_DIR/$fname" ]; then
    curl -sS -A "$UA" -o "$FONT_DIR/$fname" "$url" && echo "    + $fname" && new=$((new+1))
  fi
done <<< "$urls"

echo
echo "Done. $new new file(s). Total: $(ls "$FONT_DIR" | wc -l) WOFF2."
echo "Commit assets/fonts/ + $CSS_OUT, bump theme version, run scripts/build-release-zips.sh."

rm -f "$tmp_css"
